#ifndef OBJECT_PROP
#define OBJECT_PROP

#define ANTHILL_SIZE 160

#define FOOD_STORAGE_SIZE 40
#define FOOD_STORAGE_MAX_FOOD 250

#define FOOD_SOURCE_SIZE 15
#define FOOD_SOURCE_STORAGE_FACTOR 5.5f
#define FOOD_SOURCE_AREA 5
#define FOOD_SOURCE_REPAIR 2
#define FOOD_SOURCE_TIME_TO_GROWN 25
#define FOOD_SOURCE_MAX_SIZE 50
#define FOOD_SOURCE_GROW_VALUE 5

#endif